---
jobs:
- name: run-curl
  serial: true
  public: true
  plan: 
  - get: concourse-meetup-#3-demo
    trigger: true
  - task: run-curl
    file: concourse-meetup-#3-demo/ci/curl-cloudfare/curl-cloudfare.yml


resources:
- name: concourse-meetup-#3-demo
  type: git
  source:
    uri: git@github.com:shinji62/concourse-meetup-3-demo.git
    branch: master
    private_key: {{private-key-github-concourse}}
